### ISSUE TITLE
Support for entriesConnection?

### ISSUE THREAD

**Issue by dbrookes** [gusnips/gatsby-source-craftcms#1]
Thank you for getting this working!

Is it possible to support [entriesConnection](https://github.com/markhuot/craftql#relationships) style queries for relationships? 

If I add one into the config, then nothing appears in the Gatsby schema, it looks like it could be because an entriesConnection query returns the data nested as `data -> query -> edges` instead.

**Comment by dbrookes** [comment]
Managed to get this working by doing some more processing in gatsby-node.js inside the map, but you may come up with something better!

```
if (data[k].hasOwnProperty("edges")) {
  data[k] = data[k].edges.map(function (d, i) {
    if (typeof d.node.id !== 'undefined') {
      d.node.id = d.node.id.toString();
    }
    const node = { ...d.node };
    if (d.hasOwnProperty("relatedEntries")) {
      node.relatedEntries = d.relatedEntries
    }
    return node;
  });
}
```

Which will give you the related entries inside the gatsby schema:

```
{
  allMyQuery {
    edges {
      node {
        id
        title
        relatedEntries {
          edges {
            node {
              id
              title
            }
          }
        }
      }
    }
  }
}
```

**Comment by gusnips** [comment]
Great!! I was about to take a look at it, looks good enough for now!
I will add to the plugin, or if you could make a push request?
Thanks again
