### ISSUE TITLE
Querying Global Fields error

### ISSUE THREAD

**Issue by matthewbeta** [gusnips/gatsby-source-craftcms#4]
Hi

I am able to query entries and output the data to my templates, however Global fields are not available. Here is my code:

    // gatsby-config.js
    plugins: [
      {
			resolve: `gatsby-source-craftcms`,
			options: {
				endpoint: `http://cms.local/api`,
				token: `REDACTED`,
				query: `{
					globals: globals {
						contact {
							address
						}
					},
                    home: entries(section:[home]) {
						id
						title
						... on Home {
							subHeading
							intro
							ctaButton {
								... on CtaButtonButton {
									__typename
									text
									linkUrl
								}
							}
						}
					},
    // etc

And then in my template:

    export const query = graphql`
      query {
        home {
			title
			subHeading
			intro
			ctaButton {
				text
				linkUrl
			}
		}
		globals {
			contact {
				address
			}
		}
      }
    `
In my console I get:

    error  Cannot query field "global" on type "Query"

If I remove the `global` from the query I can successfully build and output `data.home.title`.

I've tried using the CraftQL browser in the CMS and I can successfully query globals:

[![enter image description here][1]][1] 

  [1]: https://i.stack.imgur.com/chjTo.png

However, if i use GraphiQL browser IDE in Gatsby, I get this error: ` "message": "Cannot query field \"globals\" on type \"Query\".",`

I'm confident I'm missing something but I can't find anything in the docs or in [CraftQL](https://github.com/markhuot/craftql). 

Any idea what I'm doing wrong here??

**Comment by pr1ntr** [comment]
Check your token permissions in craftql

**Comment by pr1ntr** [comment]
I am having this problem too. Is this lib still maintained?

**Comment by pr1ntr** [comment]
#6

**Comment by gusnips** [comment]
Thanks!!
